language: go
sudo: false

go:
  - 1.16.x

env:
  global:
    - CARAVAN_DEBUG=1

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - go get -u golang.org/x/tools/cmd/stringer
  - go get -u golang.org/x/lint/golint

script:
  - make test
  - go test -coverprofile c.out ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
